export const getAllUserApi = '/users/getListUser'
export const getDetailUser = '/users/getDetailUser'
export const updateUser = '/users/updateUser'
export const createUser = '/users/createUser'
export const getListMailLog = '/users/getListMailLogByUser'